#!/usr/bin/env bash

REALPATH=$(which grealpath || which realpath)
REL_PATH="$($REALPATH `pwd` --relative-to "$DUNE_SOURCEROOT")"

if [[ -n "$CPP2V_DOCKER_IMAGE" ]]; then
	BRICK_LIBCPP=/home/coq/worktree
	ARGS=()
	ARGS+=( "--platform" "linux/amd64" )
	ARGS+=( "--volume" "${HOME}/.cache/remote_dune:/home/coq/.cache/dune:cached" )
	ARGS+=( "--volume" "$DUNE_SOURCEROOT:$BRICK_LIBCPP" )
	ARGS+=( "--workdir" "$BRICK_LIBCPP/$REL_PATH" )

	CMD="$( printf '"%q" ' "$@" )" # ensure each argument is quoted as a whole.
	docker run "${ARGS[@]}" "$CPP2V_DOCKER_IMAGE" \
		/bin/bash -c 'eval $(opam env)'"; cpp2v $CMD"
else
	next=$DUNE_SOURCEROOT/_build/install/default/bin/cpp2v
	[ -e $next ] || next='opam exec -- cpp2v'
	$next "$@"
fi
