#!/usr/bin/env bash

REALPATH=$(which grealpath || which realpath)
REL_PATH="$($REALPATH `pwd` --relative-to "$DUNE_SOURCEROOT")"

if [ -n "$IN_CPP2V_DOCKER" ]; then
  echo "Error: recursive invocation of \"cpp2v_docker\" as $0 from outer cpp2v_docker as ${IN_CPP2V_DOCKER}"
  echo "(PATH is $PATH)."
  exit 1
fi

if [[ -n "$CPP2V_DOCKER_IMAGE" ]]; then
  BRICK_LIBCPP=/home/coq/worktree
  ARGS=()
  ARGS+=( "--platform" "linux/amd64" )
  ARGS+=( "--volume" "${HOME}/.cache/remote_dune:/home/coq/.cache/dune:cached" )
  ARGS+=( "--volume" "$DUNE_SOURCEROOT:$BRICK_LIBCPP" )
  ARGS+=( "--workdir" "$BRICK_LIBCPP/$REL_PATH" )

  cpp2v_args="$( printf '"%q" ' "$@" )" # ensure each argument is quoted as a whole.
  docker run "${ARGS[@]}" "$CPP2V_DOCKER_IMAGE" \
          /bin/bash -c 'eval $(opam env)'"; cpp2v $cpp2v_args"
else
  export IN_CPP2V_DOCKER="$0"
  next=$DUNE_SOURCEROOT/_build/install/default/bin/cpp2v
  [ -e $next ] || next='opam exec -- cpp2v'
  exec $next "$@"
fi
