(rule
 (target cpp2v_docker)
 (deps
  (universe)
  (:sha1sum %{bin:sha1sum})
  (:template cpp2v_docker.in))
 (action
  (progn
   (with-stdout-to
    %{target}
    (bash
     "set -eu
hash=$(%{sha1sum} %{bin:cpp2v} | cut -d ' ' -f 1)
image_id=
if command -v docker >/dev/null 2>&1; then
  image_id=$(docker inspect --format='{{.Id}}' skylabsai/fm-releases:fm-release-nightly 2>/dev/null || true)
fi
sed -e \"s/@CPP2V_SHA1@/$hash/g\" -e \"s/@CPP2V_DOCKER_IMAGE_ID@/$image_id/g\" %{template}"))
   (run chmod +x %{target}))))

(env
 (_
  (flags :standard %{read-lines:flags/ocamlc})
  (ocamlopt_flags :standard -O3 -unbox-closures)
  (rocq
   (rocqdep_flags :standard -w +all)
   (flags
    (:standard
      %{read-lines:flags/coqc}
      -w +sl-transparent-constants
)))))
