(*
 * Specification for [bool std::optional<int>::has_value() const].
 *
 * Generated by the Spec Agent (gpt-5.6-sol, reasoning effort xhigh) from the
 * frozen requirement set in 1-obligations.md. Verbatim, unedited.
 *
 * These are three files in the tree, shown here in dependency order for
 * reading: model.v, pred.v, spec.v. Only [has_value] is a pinned observable.
 * The constructors, assignment, [reset] and [emplace] contracts exist so a
 * client can reach a known engagement state before asking [has_value()].
 *)

(* ==================================================================
   proof/optional/model.v -- abstract state model
   ================================================================== *)
(*
 * Copyright (c) 2026 SkyLabs AI, Inc.
 * This software is distributed under the terms of the BedRock Open-Source License.
 * See the LICENSE-BedRock file in the repository root for details.
 *)
Require Import skylabs.prelude.base.

#[local] Open Scope Z_scope.

(** Public state model for [std::optional<int>]. *)
Definition optional_state : Type := option Z.

(** Whether an optional state contains a value. *)
Definition is_engaged (state : optional_state) : bool :=
  match state with
  | None => false
  | Some _ => true
  end.

Succeed Example is_engaged_none : is_engaged None = false := eq_refl.
Succeed Example is_engaged_zero : is_engaged (Some 0) = true := eq_refl.
Succeed Example is_engaged_value : is_engaged (Some 5) = true := eq_refl.

(* ==================================================================
   proof/optional/pred.v -- ownership predicate
   ================================================================== *)
(*
 * Copyright (c) 2026 SkyLabs AI, Inc.
 * This software is distributed under the terms of the BedRock Open-Source License.
 * See the LICENSE-BedRock file in the repository root for details.
 *)
Require Import skylabs.auto.cpp.prelude.spec.
Require Import skylabs.cpp.spec.concepts.

Require Export skylabs.brick.libstdcpp.optional.model.

#[global] Abbreviation optionalN :=
  (Ninst "std::optional" [Atype Tint]).
#[global] Abbreviation optionalT := (Tnamed optionalN).
#[global] Abbreviation nulloptT := (Tnamed "std::nullopt_t").

Section with_cpp.
  Context `{Σ : cpp_logic, σ : genv}.

  (** Fractional ownership of a [std::optional<int>] in [state]. *)
  Parameter optionalR : cQp.t -> optional_state -> Rep.
  #[only(cfractional,cfracvalid,ascfractional,type_ptr="std::optional<int>")]
    derive optionalR.

  #[global] Declare Instance optionalR_agree q1 q2 state1 state2 :
    Observe2 [| state1 = state2 |]
      (optionalR q1 state1) (optionalR q2 state2).

  #[global] Instance optional_has_rep :
    concepts.BundledRep optionalT optional_state :=
    {| objR := optionalR |}.

End with_cpp.

(* ==================================================================
   proof/optional/spec.v -- the contracts
   ================================================================== *)
(*
 * Copyright (c) 2026 SkyLabs AI, Inc.
 * This software is distributed under the terms of the BedRock Open-Source License.
 * See the LICENSE-BedRock file in the repository root for details.
 *)
Require Import skylabs.auto.cpp.spec.
Require Import skylabs.cpp.spec.concepts.

Require Export skylabs.brick.libstdcpp.optional.pred.
Require Import skylabs.brick.libstdcpp.optional.inc_optional_cpp.

(* [specify]'s string/notation form (as in [tests/specify/templates.v]) is the
   only registration idiom that can express a constructor/member *template*
   instantiation, whose emitted name is a doubly-nested
   [Ninst (Nscoped (Ninst optional [..]) (Nctor/Nfunction/Nop ..)) [..]].
   The [specify.template.*] combinators only build a single-[Ninst] name (a
   member of a class-template instantiation), so they cannot register these. *)
Import specify_notation.

Section with_cpp.
  Context `{Σ : cpp_logic, σ : genv}.

  Definition default_ctor_spec :=
    specify.template.ctor optionalN [] $
      \this this
      \post this |-> optionalR 1$m None.
  #[global] Hint Opaque default_ctor_spec : sl_opacity.
  #[global] Arguments default_ctor_spec : simpl never.
  Definition default_ctor_spec_instance := RegisterSpec default_ctor_spec.
  #[global] Existing Instance default_ctor_spec_instance.

  Definition nullopt_ctor_spec :=
    specify.template.ctor optionalN [nulloptT] $
      \this this
      \arg{tagp} "" (Vptr tagp)
      \post this |-> optionalR 1$m None.
  #[global] Hint Opaque nullopt_ctor_spec : sl_opacity.
  #[global] Arguments nullopt_ctor_spec : simpl never.
  Definition nullopt_ctor_spec_instance := RegisterSpec nullopt_ctor_spec.
  #[global] Existing Instance nullopt_ctor_spec_instance.

  (* [std::optional<int>::optional(int&&)] is the constrained converting
     constructor template [template<class U = T> optional(U&&)]; cpp2v emits its
     required call as the instantiation
     [std::optional<int>::optional<int, 1b>(int&&)], i.e.
     [Ninst (Nscoped optionalN (Nctor [Trv_ref Tint])) [Atype Tint; Avalue (Eint 1 Tbool)]].
     It must be registered as a template instantiation so the template dispatch
     can consume it. *)
  Definition value_ctor_def :=
    specify (tCtor optionalN [Trv_ref Tint])
      "std::optional<int>::optional<int, 1b>(int&&)"%cpp_name (
      \this this
      \arg{valuep} "__t" (Vref valuep)
      \prepost{q value} valuep |-> intR q value
      \post this |-> optionalR 1$m (Some value)).
  Definition value_ctor_spec := Hnf (fst value_ctor_def).
  #[global] Hint Opaque value_ctor_spec : sl_opacity.
  #[global] Arguments value_ctor_spec : simpl never.
  Definition value_ctor_spec_instance := Hnf (snd value_ctor_def value_ctor_spec).
  #[global] Existing Instance value_ctor_spec_instance.

  Definition copy_ctor_spec :=
    specify.template.ctor optionalN [Tref (Tconst optionalT)] $
      \this this
      \arg{otherp} "" (Vref otherp)
      \prepost{q state} otherp |-> optionalR q state
      \post this |-> optionalR 1$m state.
  #[global] Hint Opaque copy_ctor_spec : sl_opacity.
  #[global] Arguments copy_ctor_spec : simpl never.
  Definition copy_ctor_spec_instance := RegisterSpec copy_ctor_spec.
  #[global] Existing Instance copy_ctor_spec_instance.

  Definition move_ctor_spec :=
    specify.template.ctor optionalN [Trv_ref optionalT] $
      \this this
      \arg{otherp} "" (Vref otherp)
      \prepost{state} otherp |-> optionalR 1$m state
      \post this |-> optionalR 1$m state.
  #[global] Hint Opaque move_ctor_spec : sl_opacity.
  #[global] Arguments move_ctor_spec : simpl never.
  Definition move_ctor_spec_instance := RegisterSpec move_ctor_spec.
  #[global] Existing Instance move_ctor_spec_instance.

  Definition dtor_spec :=
    specify.template.dtor optionalN $
      \this this
      \pre{state} this |-> optionalR 1$m state
      \post emp.
  #[global] Hint Opaque dtor_spec : sl_opacity.
  #[global] Arguments dtor_spec : simpl never.
  Definition dtor_spec_instance := RegisterSpec dtor_spec.
  #[global] Existing Instance dtor_spec_instance.

  Definition nullopt_assign_spec :=
    specify.template.op optionalN OOEqual function_qualifiers.N
      (Tref optionalT) [nulloptT] $
      \this this
      \arg{tagp} "" (Vptr tagp)
      \pre{state} this |-> optionalR 1$m state
      \post[Vref this] this |-> optionalR 1$m None.
  #[global] Hint Opaque nullopt_assign_spec : sl_opacity.
  #[global] Arguments nullopt_assign_spec : simpl never.
  Definition nullopt_assign_spec_instance := RegisterSpec nullopt_assign_spec.
  #[global] Existing Instance nullopt_assign_spec_instance.

  (* Converting assignment operator template
     [template<class U = T> optional& operator=(U&&)]; cpp2v emits the required
     call as the instantiation [std::optional<int>::operator=<int>(int&&)], i.e.
     [Ninst (Nscoped optionalN (Nop N OOEqual [Trv_ref Tint])) [Atype Tint]].
     Registered as a template instantiation, as for [value_ctor_spec]. *)
  Definition value_assign_def :=
    specify
      (tMethod optionalN
        (function_qualifiers.to_type_qualifiers function_qualifiers.N)
        (Tref optionalT) [Trv_ref Tint])
      "std::optional<int>::operator=<int>(int&&)"%cpp_name (
      \this this
      \arg{valuep} "__u" (Vref valuep)
      \prepost{q value} valuep |-> intR q value
      \pre{state} this |-> optionalR 1$m state
      \post[Vref this] this |-> optionalR 1$m (Some value)).
  Definition value_assign_spec := Hnf (fst value_assign_def).
  #[global] Hint Opaque value_assign_spec : sl_opacity.
  #[global] Arguments value_assign_spec : simpl never.
  Definition value_assign_spec_instance := Hnf (snd value_assign_def value_assign_spec).
  #[global] Existing Instance value_assign_spec_instance.

  (* Move-assignment special member [optional& operator=(optional&&)]. For a
     [std::optional<int>] this is a plain member of the class-template
     instantiation, so cpp2v emits it as
     [Nscoped optionalN (Nop N OOEqual [Trv_ref optionalT])] and it is
     registered with [specify.template.op], exactly as [nullopt_assign_spec].
     Assigning an engaged source leaves [this] engaged (its state becomes the
     source's state); as for [move_ctor_spec] the moved-from source retains its
     abstract state. *)
  Definition move_assign_spec :=
    specify.template.op optionalN OOEqual function_qualifiers.N
      (Tref optionalT) [Trv_ref optionalT] $
      \this this
      \arg{otherp} "" (Vref otherp)
      \prepost{state} otherp |-> optionalR 1$m state
      \pre{old} this |-> optionalR 1$m old
      \post[Vref this] this |-> optionalR 1$m state.
  #[global] Hint Opaque move_assign_spec : sl_opacity.
  #[global] Arguments move_assign_spec : simpl never.
  Definition move_assign_spec_instance := RegisterSpec move_assign_spec.
  #[global] Existing Instance move_assign_spec_instance.

  (* [emplace] is the variadic member template
     [template<class... Args> T& emplace(Args&&...)]; for the single-[int]
     argument call cpp2v instantiates the [Args] pack and emits the name
     [std::optional<int>::emplace<...<int>>(int&&)], i.e. the enclosing
     [Ninst]'s template-argument list is a *pack* [Apack [Atype Tint]] (as for
     [std::construct_at<char, ...>] in the string binding), NOT the bare
     [[Atype Tint]] a non-variadic instantiation would produce. *)
  Definition emplace_spec :=
    _global (Ninst
      (Nscoped optionalN
        (Nfunction function_qualifiers.N "emplace" [Trv_ref Tint]))
      [Apack [Atype Tint]]) |->
    unmaterialized_specR
      (tMethod optionalN
        (function_qualifiers.to_type_qualifiers function_qualifiers.N)
        (Tref Tint) [Trv_ref Tint]) (
      \this this
      \arg{valuep} "__args" (Vref valuep)
      \prepost{q value} valuep |-> intR q value
      \pre{state} this |-> optionalR 1$m state
      \post{result}[Vref result] this |-> optionalR 1$m (Some value)).
  #[global] Hint Opaque emplace_spec : sl_opacity.
  #[global] Arguments emplace_spec : simpl never.
  Definition emplace_spec_instance := RegisterSpec emplace_spec.
  #[global] Existing Instance emplace_spec_instance.

  Definition reset_spec :=
    specify.template.method optionalN "reset" function_qualifiers.N Tvoid [] $
      \this this
      \pre{state} this |-> optionalR 1$m state
      \post this |-> optionalR 1$m None.
  #[global] Hint Opaque reset_spec : sl_opacity.
  #[global] Arguments reset_spec : simpl never.
  Definition reset_spec_instance := RegisterSpec reset_spec.
  #[global] Existing Instance reset_spec_instance.

  Definition has_value_spec :=
    specify.template.method optionalN "has_value" function_qualifiers.Nc Tbool [] $
      \this this
      \prepost{q state} this |-> optionalR q state
      \post[Vbool (is_engaged state)] emp.
  #[global] Hint Opaque has_value_spec : sl_opacity.
  #[global] Arguments has_value_spec : simpl never.
  Definition has_value_spec_spec_instance := RegisterSpec has_value_spec.
  #[global] Existing Instance has_value_spec_spec_instance.

  (* [RegisterSpec] keys its [SpecFor] on the emitted member name
     [Nscoped (Ninst optional ..) (Nfunction .. "has_value" ..)], which is what
     the [x.has_value()] call sites dispatch on. The public-registration ledger,
     however, identifies the contract by the bare API name [has_value] in the
     translation unit, so expose the same [has_value_spec] payload under that key
     too. Keyed on a distinct name, this never competes with the member dispatch
     above. *)
  #[global] Instance has_value_named_spec_instance :
    SpecFor inc_optional_cpp.source "has_value" :=
    SpecFor.mk inc_optional_cpp.source "has_value" has_value_spec.

  (* [std::nullopt_t] is the empty tag class behind [std::nullopt]. cpp2v emits
     its implicit copy-constructor and destructor as ordinary (non-template)
     members. Constructing a [std::optional<int>] from [std::nullopt] first
     materializes a [nullopt_t] temporary (copied from the [std::nullopt] global)
     and later destroys it, so both members are required. The [specify.template.*]
     combinators above only build single-[Ninst] names, so these plain members are
     registered with [specify.exact.*] on the empty-struct ownership [structR]. *)
  Definition nulloptN : name := "std::nullopt_t"%cpp_name.

  Definition nullopt_copy_ctor_spec :=
    specify.exact.ctor nulloptN [Tref (Tconst nulloptT)] $
      \this this
      \arg{otherp} "" (Vref otherp)
      \prepost{q} otherp |-> structR nulloptN q
      \post this |-> structR nulloptN 1$m.
  #[global] Hint Opaque nullopt_copy_ctor_spec : sl_opacity.
  #[global] Arguments nullopt_copy_ctor_spec : simpl never.
  Definition nullopt_copy_ctor_spec_instance := RegisterSpec nullopt_copy_ctor_spec.
  #[global] Existing Instance nullopt_copy_ctor_spec_instance.

  Definition nullopt_dtor_spec :=
    specify.exact.dtor nulloptN $
      \this this
      \pre this |-> structR nulloptN 1$m
      \post emp.
  #[global] Hint Opaque nullopt_dtor_spec : sl_opacity.
  #[global] Arguments nullopt_dtor_spec : simpl never.
  Definition nullopt_dtor_spec_instance := RegisterSpec nullopt_dtor_spec.
  #[global] Existing Instance nullopt_dtor_spec_instance.

  (* [std::nullopt] is the global [constexpr const std::nullopt_t nullopt];
     cpp2v emits it as the [Dvariable] named [std::nullopt] of type
     [const std::nullopt_t]. Materializing a [nullopt_t] temporary from it (as
     [std::optional<int>(std::nullopt)] does) copies out of this global, so the
     copy-constructor's source [\prepost{q} .. |-> structR nulloptN q] must be
     satisfied at the global's address. A [const]-qualified global with static
     storage is constant-initialized before any use and never mutated, so a
     read-only ([1$c]) view of its (empty) [structR] is a sound resource to hand
     to callers. It is exposed through the [SpecFor] database keyed on the
     variable's name so that [verify]'s dependency collection picks it up for any
     client that references the global -- the same database the [RegisterSpec]
     members above populate. This is a resource, not a callable spec, so it is
     registered directly rather than via [RegisterSpec]. *)
  #[global] Instance nullopt_global_spec_instance (tu : translation_unit) :
    SpecFor tu "std::nullopt"%cpp_name :=
    SpecFor.mk tu _ (_global "std::nullopt" |-> structR nulloptN 1$c).

End with_cpp.
