(rule
 (target cpp2v_docker)
 (deps
  (:sha1sum %{bin:sha1sum})
  (:template ../rocq-brick-libstdcpp/cpp2v_docker.in)
  (package rocq-skylabs-cpp2v))
 (action
  (progn
   (with-stdout-to
    %{target}
    (bash
     "set -eu
hash=$(%{sha1sum} %{bin:cpp2v} | cut -d ' ' -f 1)
sed \"s/@CPP2V_SHA1@/$hash/g\" %{template}"))
   (run chmod +x %{target}))))
