#!/usr/bin/env bash

usage() {
	cat >&2 <<-EOF
		usage: $(basename "$0")

		This will invoke ./cpp2v-dune-gen.sh for every C or C++ file under
		the current directory, sending the dune rules to ${target}.
	EOF
        exit 1
}

[ $# = 0 ] || usage

echo "; DO NOT EDIT: Generated by \"$0${1+ $*}\""

# Temporary: `cpp2v --templates` for only those tests in ./templates.

# Blacklist some files for arch_indep
find . -name '*.[ch]pp' |
LC_ALL=C sort |
while read i; do
  args=""
  if [[ $i =~ ^./(algorithms|vector)/.* ]]; then
     args+="-t"
  fi
  ./cpp2v-dune-gen.sh -s ${args} -- $i -- -std=c++20 -stdlib=libstdc++
done
